import {
  Injectable,
  Logger,
  BadRequestException,
  ForbiddenException,
  NotFoundException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../prisma/prisma.service';
import { GmailService } from './gmail.service';
import { GmailOAuthService } from './gmail-oauth.service';
import { MailpitService } from './mailpit.service';
import {
  SendEmailDto,
  SendVisitReportDto,
} from './dto/send-email.dto';
import { GmailSyncService } from './gmail-sync.service';

type ResolvedAttachment = {
  filename: string;
  mimeType: string;
  content: Buffer;
};

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);

  private readonly emailProvider: string;

  private readonly MAX_ATTACHMENT_SIZE =
    10 * 1024 * 1024;

  private readonly MAX_TOTAL_ATTACHMENT_SIZE =
    20 * 1024 * 1024;

  private readonly ALLOWED_ATTACHMENT_TYPES = [
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ];

  constructor(
    private readonly configService: ConfigService,
    private readonly prisma: PrismaService,
    private readonly gmailService: GmailService,
    private readonly gmailOAuthService: GmailOAuthService,
    private readonly mailpitService: MailpitService,
    private readonly gmailSyncService: GmailSyncService,
  ) {
    this.emailProvider =
      this.configService.get<string>(
        'EMAIL_PROVIDER',
      ) || 'gmail';

    this.logger.log(
      `Email provider: ${this.emailProvider}`,
    );
  }

  /**
   * Send an email from an employee.
   *
   * Every email generated by Kshetra is forced to contain
   * [KSHETRA] in the subject. This is important because
   * Phase 2 inbox synchronization uses that marker to keep
   * unrelated Gmail messages out of Kshetra.
   */
  async sendEmail(
    employeeId: string,
    dto: SendEmailDto,
    preResolvedAttachments?: ResolvedAttachment[],
  ): Promise<{
    id: string;
    status: string;
    gmailMessageId?: string;
  }> {
    if (!this.isValidEmail(dto.to)) {
      throw new BadRequestException(
        'Invalid recipient email address.',
      );
    }

    if (dto.cc?.length) {
      for (const cc of dto.cc) {
        if (!this.isValidEmail(cc)) {
          throw new BadRequestException(
            `Invalid CC email address: ${cc}`,
          );
        }
      }
    }

    if (!dto.subject?.trim()) {
      throw new BadRequestException(
        'Email subject is required.',
      );
    }

    if (!dto.body?.trim()) {
      throw new BadRequestException(
        'Email body is required.',
      );
    }

    const employee =
      await this.prisma.employee.findUnique({
        where: {
          id: employeeId,
        },
      });

    if (!employee) {
      throw new NotFoundException(
        'Employee not found.',
      );
    }

    if (employee.status === 'INACTIVE') {
      throw new ForbiddenException(
        'Your account is deactivated.',
      );
    }

    let customerSiteId:
      | string
      | undefined;

    if (dto.customerSiteId) {
      const site =
        await this.prisma.customerSite.findUnique({
          where: {
            id: dto.customerSiteId,
          },
        });

      if (!site) {
        throw new NotFoundException(
          'Customer site not found.',
        );
      }

      customerSiteId = site.id;
    }

    const attachments =
      preResolvedAttachments ??
      (await this.resolveAttachments(
        employeeId,
        dto.attachmentUrls || [],
      ));

    this.validateResolvedAttachments(
      attachments,
    );

    const normalizedSubject =
      this.normalizeKshetraSubject(
        dto.subject,
      );

    let senderEmail =
      'unknown@kshetra.local';

    if (
      this.emailProvider === 'gmail'
    ) {
      const status =
        await this.gmailOAuthService.getConnectionStatus(
          employeeId,
        );

      if (!status.connected) {
        throw new BadRequestException(
          'Gmail is not connected. Please connect your Gmail account first.',
        );
      }

      senderEmail =
        status.gmailAddress!;
    } else {
      senderEmail =
        `${employeeId}@kshetra.local`;
    }

    const emailLog =
      await this.prisma.emailLog.create({
        data: {
          employeeId,

          customerSiteId:
            customerSiteId || null,

          senderEmail,

          recipientEmail:
            dto.to,

          ccEmails:
            dto.cc || [],

          subject:
            normalizedSubject,

          bodyPreview:
            dto.body.substring(
              0,
              200,
            ),

          status:
            'QUEUED',

          attachmentCount:
            attachments.length,
        },
      });

    try {
      let gmailMessageId:
        | string
        | undefined;

      if (
        this.emailProvider ===
        'mailpit'
      ) {
        const result =
          await this.mailpitService.sendEmail(
            {
              from:
                senderEmail,

              to:
                dto.to,

              cc:
                dto.cc,

              subject:
                normalizedSubject,

              body:
                dto.body,

              attachments:
                attachments.map(
                  (attachment) => ({
                    filename:
                      attachment.filename,

                    content:
                      attachment.content,

                    contentType:
                      attachment.mimeType,
                  }),
                ),
            },
          );

        gmailMessageId =
          result.messageId;
      } else {
        const result =
          await this.gmailService.sendEmail(
            employeeId,
            {
              to:
                dto.to,

              cc:
                dto.cc,

              subject:
                normalizedSubject,

              body:
                dto.body,

              attachments:
                attachments.length >
                0
                  ? attachments
                  : undefined,
            },
          );

        gmailMessageId =
          result.messageId;
      }

      await this.prisma.emailLog.update(
        {
          where: {
            id:
              emailLog.id,
          },

          data: {
            status:
              'SENT',

            gmailMessageId,

            sentAt:
              new Date(),
          },
        },
      );

      return {
        id:
          emailLog.id,

        status:
          'SENT',

        gmailMessageId,
      };
    } catch (error: any) {
      await this.prisma.emailLog.update(
        {
          where: {
            id:
              emailLog.id,
          },

          data: {
            status:
              'FAILED',

            errorMessage:
              error?.message?.substring(
                0,
                500,
              ),
          },
        },
      );

      throw error;
    }
  }

  /**
   * Send a field visit report.
   *
   * Photos are resolved directly from the employee-owned visit
   * instead of being discarded by passing attachmentUrls: [].
   */
  async sendVisitReport(
    employeeId: string,
    dto: SendVisitReportDto,
  ): Promise<{
    id: string;
    status: string;
    gmailMessageId?: string;
  }> {
    if (
      !this.isValidEmail(
        dto.recipientEmail,
      )
    ) {
      throw new BadRequestException(
        'Invalid recipient email address.',
      );
    }

    const visit =
      await this.prisma.fieldVisit.findFirst(
        {
          where: {
            id:
              dto.fieldVisitId,

            employeeId,
          },

          include: {
            site: true,

            location: true,

            attachments: true,

            materials: {
              include: {
                material: true,
              },
            },

            followUps: true,

            employee: {
              select: {
                name: true,
                id: true,
              },
            },
          },
        },
      );

    if (!visit) {
      throw new NotFoundException(
        'Field visit not found or you do not have permission to access it.',
      );
    }

    const reportBody =
      this.buildVisitReportBody(
        visit,
        dto.additionalNotes,
      );

    let attachments:
      ResolvedAttachment[] =
      [];

    if (
      dto.includePhotos &&
      visit.attachments.length > 0
    ) {
      attachments =
        await this.fetchVisitPhotos(
          visit.attachments,
        );
    }

    this.validateResolvedAttachments(
      attachments,
    );

    const subject =
      `Field Visit Report — ${
        visit.site?.name ||
        'Unknown Site'
      } — ${new Date(
        visit.timestamp,
      ).toLocaleDateString(
        'en-IN',
      )}`;

    const result =
      await this.sendEmail(
        employeeId,
        {
          to:
            dto.recipientEmail,

          cc:
            dto.cc,

          subject,

          body:
            reportBody,

          customerSiteId:
            visit.customerSiteId,

          attachmentUrls: [],
        },
        attachments,
      );

    await this.prisma.emailLog.update({
      where: {
        id:
          result.id,
      },

      data: {
        fieldVisitId:
          visit.id,

        isVisitReport:
          true,
      },
    });

    return result;
  }

  /**
   * Get sent email history.
   *
   * Only Kshetra emails are returned.
   */
  async getEmailHistory(
    employeeId: string,
    page = 1,
    limit = 20,
  ) {
    const skip =
      (page - 1) * limit;

    const where: any = {
      employeeId,

      subject: {
        contains:
          '[KSHETRA]',

        mode:
          'insensitive',
      },
    };

    const [
      emails,
      total,
    ] = await Promise.all([
      this.prisma.emailLog.findMany(
        {
          where,

          skip,

          take: limit,

          orderBy: {
            createdAt:
              'desc',
          },

          select: {
            id: true,

            recipientEmail:
              true,

            subject:
              true,

            status:
              true,

            sentAt:
              true,

            createdAt:
              true,

            isVisitReport:
              true,

            attachmentCount:
              true,

            customerSite: {
              select: {
                id: true,
                name: true,
              },
            },

            fieldVisitId:
              true,
          },
        },
      ),

      this.prisma.emailLog.count({
        where,
      }),
    ]);

    return {
      emails,
      total,
      page,
      limit,
    };
  }

  async getEmailDetail(
    employeeId: string,
    emailId: string,
  ) {
    const email =
      await this.prisma.emailLog.findFirst(
        {
          where: {
            id:
              emailId,

            employeeId,

            subject: {
              contains:
                '[KSHETRA]',

              mode:
                'insensitive',
            },
          },

          include: {
            customerSite: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      );

    if (!email) {
      throw new NotFoundException(
        'Email not found.',
      );
    }

    return {
      id:
        email.id,

      senderEmail:
        email.senderEmail,

      recipientEmail:
        email.recipientEmail,

      ccEmails:
        email.ccEmails,

      subject:
        email.subject,

      bodyPreview:
        email.bodyPreview,

      status:
        email.status,

      errorMessage:
        email.status ===
        'FAILED'
          ? email.errorMessage
          : undefined,

      attachmentCount:
        email.attachmentCount,

      isVisitReport:
        email.isVisitReport,

      fieldVisitId:
        email.fieldVisitId,

      customerSite:
        email.customerSite,

      sentAt:
        email.sentAt,

      createdAt:
        email.createdAt,
    };
  }

  /**
   * Phase 2 inbox.
   *
   * The database may already contain old/non-Kshetra threads.
   * Therefore filtering only Gmail synchronization is insufficient.
   * This query explicitly filters them out.
   */
  async getEmployeeEmailThreads(
    employeeId: string,
    page = 1,
    limit = 30,
    customerSiteId?: string,
  ) {
    const employee =
      await this.prisma.employee.findUnique(
        {
          where: {
            id:
              employeeId,
          },

          select: {
            id: true,
            name: true,
          },
        },
      );

    if (!employee) {
      throw new NotFoundException(
        'Employee not found.',
      );
    }

    const where: any = {
      employeeId,

      subject: {
        contains:
          '[KSHETRA]',

        mode:
          'insensitive',
      },
    };

    if (customerSiteId) {
      where.customerSiteId =
        customerSiteId;
    }

    const [
      threads,
      total,
    ] = await Promise.all([
      this.prisma.emailThread.findMany(
        {
          where,

          include: {
            customerSite: {
              select: {
                id: true,
                name: true,
                email: true,
              },
            },

            messages: {
              orderBy: {
                sentAt:
                  'desc',
              },

              take: 1,
            },
          },

          orderBy: {
            lastMessageAt:
              'desc',
          },

          skip:
            (page - 1) *
            limit,

          take:
            limit,
        },
      ),

      this.prisma.emailThread.count(
        {
          where,
        },
      ),
    ]);

    return {
      threads,
      total,
      page,
      limit,
    };
  }

  async getEmailThread(
    employeeId: string,
    threadId: string,
  ) {
    const thread =
      await this.prisma.emailThread.findFirst(
        {
          where: {
            id:
              threadId,

            employeeId,

            subject: {
              contains:
                '[KSHETRA]',

              mode:
                'insensitive',
            },
          },

          include: {
            customerSite: {
              select: {
                id: true,
                name: true,
                email: true,
              },
            },

            messages: {
              orderBy: {
                sentAt:
                  'asc',
              },
            },
          },
        },
      );

    if (!thread) {
      throw new NotFoundException(
        'Email conversation not found.',
      );
    }

    return thread;
  }

  async getThreadForAdmin(
    threadId: string,
  ) {
    const thread =
      await this.prisma.emailThread.findFirst(
        {
          where: {
            id:
              threadId,

            subject: {
              contains:
                '[KSHETRA]',

              mode:
                'insensitive',
            },
          },

          include: {
            customerSite: {
              select: {
                id: true,
                name: true,
                email: true,
              },
            },

            messages: {
              orderBy: {
                sentAt:
                  'asc',
              },
            },
          },
        },
      );

    if (!thread) {
      throw new NotFoundException(
        'Email conversation not found.',
      );
    }

    return thread;
  }

  async syncEmployeeEmail(
    employeeId: string,
  ) {
    return this.gmailSyncService.syncEmployee(
      employeeId,
    );
  }

  /**
   * Reply to the latest CUSTOMER message.
   *
   * Important:
   * Do NOT select the latest message blindly.
   * Once an employee has replied, their outbound message becomes
   * the newest message and would otherwise cause the reply to be
   * sent to the employee themselves.
   */
  async replyToThread(
    employeeId: string,
    threadId: string,
    body: string,
  ) {
    if (!body?.trim()) {
      throw new BadRequestException(
        'Reply body is required.',
      );
    }

    const thread =
      await this.prisma.emailThread.findFirst(
        {
          where: {
            id:
              threadId,

            employeeId,

            subject: {
              contains:
                '[KSHETRA]',

              mode:
                'insensitive',
            },
          },

          include: {
            messages: {
              where: {
                direction:
                  'INBOUND',
              },

              orderBy: {
                sentAt:
                  'desc',
              },

              take: 1,
            },
          },
        },
      );

    if (!thread) {
      throw new NotFoundException(
        'Email conversation not found.',
      );
    }

    const latestCustomerMessage =
      thread.messages[0];

    if (!latestCustomerMessage) {
      throw new BadRequestException(
        'There is no customer message to reply to in this conversation.',
      );
    }

    const to =
      latestCustomerMessage.fromEmail;

    if (!this.isValidEmail(to)) {
      throw new BadRequestException(
        'Customer email address is invalid.',
      );
    }

    const baseSubject =
      latestCustomerMessage.subject ||
      thread.subject ||
      'Email conversation';

    const replySubject =
      this.ensureReplySubject(
        baseSubject,
      );

    const result =
      await this.gmailService.replyToThread(
        employeeId,
        {
          threadId:
            thread.gmailThreadId,

          to,

          subject:
            replySubject,

          body,

          inReplyTo:
            latestCustomerMessage.messageId ||
            undefined,

          references:
            latestCustomerMessage.references ||
            latestCustomerMessage.messageId ||
            undefined,
        },
      );

    const senderConnection =
      await this.prisma.gmailConnection.findUnique(
        {
          where: {
            employeeId,
          },

          select: {
            gmailAddress:
              true,
          },
        },
      );

    if (!senderConnection) {
      throw new BadRequestException(
        'Gmail connection not found.',
      );
    }

    const sentAt =
      new Date();

    const message =
      await this.prisma.emailMessage.create(
        {
          data: {
            threadId:
              thread.id,

            employeeId,

            gmailMessageId:
              result.messageId,

            gmailThreadId:
              result.threadId ||
              thread.gmailThreadId,

            direction:
              'OUTBOUND',

            fromEmail:
              senderConnection.gmailAddress,

            toEmails: [
              to,
            ],

            ccEmails: [],

            subject:
              replySubject,

            bodyText:
              body,

            bodyHtml:
              this.plainTextToHtml(
                body,
              ),

            snippet:
              body.substring(
                0,
                200,
              ),

            isRead:
              true,

            sentAt,
          },
        },
      );

    await this.prisma.emailThread.update(
      {
        where: {
          id:
            thread.id,
        },

        data: {
          subject:
            replySubject,

          lastMessageAt:
            sentAt,

          unreadCount:
            0,
        },
      },
    );

    /*
     * IMPORTANT:
     *
     * Flutter's SendEmailResult expects the fields below at
     * the top level. The old implementation returned:
     *
     * {
     *   success: true,
     *   message: {...}
     * }
     *
     * which caused the email to be sent successfully but then
     * Flutter crashed trying to read json['id'].
     */
    return {
      id:
        message.id,

      status:
        'SENT',

      gmailMessageId:
        message.gmailMessageId,

      threadId:
        message.gmailThreadId,
    };
  }

  async forwardMessage(
    employeeId: string,
    messageId: string,
    to: string,
    body: string,
  ) {
    if (!this.isValidEmail(to)) {
      throw new BadRequestException(
        'Invalid recipient email address.',
      );
    }

    if (!body?.trim()) {
      throw new BadRequestException(
        'Forward body is required.',
      );
    }

    const original =
      await this.prisma.emailMessage.findFirst(
        {
          where: {
            id:
              messageId,

            employeeId,
          },
        },
      );

    if (!original) {
      throw new NotFoundException(
        'Email message not found.',
      );
    }

    if (
      !this.isKshetraSubject(
        original.subject,
      )
    ) {
      throw new ForbiddenException(
        'Only Kshetra email messages can be forwarded.',
      );
    }

    const subject =
      original.subject ||
      '[KSHETRA] Email';

    const originalBody =
      original.bodyText ||
      '';

    const result =
      await this.gmailService.forwardMessage(
        employeeId,
        {
          to,

          subject,

          body,

          originalBody,
        },
      );

    const senderConnection =
      await this.prisma.gmailConnection.findUnique(
        {
          where: {
            employeeId,
          },

          select: {
            gmailAddress:
              true,
          },
        },
      );

    if (!senderConnection) {
      throw new BadRequestException(
        'Gmail connection not found.',
      );
    }

    const sentAt =
      new Date();

    const forwardSubject =
      this.ensureForwardSubject(
        subject,
      );

    const thread =
      await this.prisma.emailThread.create(
        {
          data: {
            employeeId,

            customerSiteId:
              null,

            gmailThreadId:
              result.threadId,

            subject:
              forwardSubject,

            participants: [
              senderConnection.gmailAddress,
              to,
            ],

            lastMessageAt:
              sentAt,

            unreadCount:
              0,
          },
        },
      );

    const message =
      await this.prisma.emailMessage.create(
        {
          data: {
            threadId:
              thread.id,

            employeeId,

            gmailMessageId:
              result.messageId,

            gmailThreadId:
              result.threadId,

            direction:
              'OUTBOUND',

            fromEmail:
              senderConnection.gmailAddress,

            toEmails: [
              to,
            ],

            ccEmails: [],

            subject:
              forwardSubject,

            bodyText:
              body,

            bodyHtml:
              this.plainTextToHtml(
                body,
              ),

            snippet:
              body.substring(
                0,
                200,
              ),

            isRead:
              true,

            sentAt,
          },
        },
      );

    return {
      id:
        message.id,

      status:
        'SENT',

      gmailMessageId:
        message.gmailMessageId,

      threadId:
        message.gmailThreadId,
    };
  }

  async markThreadRead(
    employeeId: string,
    threadId: string,
  ) {
    const thread =
      await this.prisma.emailThread.findFirst(
        {
          where: {
            id:
              threadId,

            employeeId,

            subject: {
              contains:
                '[KSHETRA]',

              mode:
                'insensitive',
            },
          },

          include: {
            messages: true,
          },
        },
      );

    if (!thread) {
      throw new NotFoundException(
        'Email conversation not found.',
      );
    }

    const unreadMessages =
      thread.messages.filter(
        (message) =>
          !message.isRead &&
          message.direction ===
            'INBOUND',
      );

    for (const message of unreadMessages) {
      try {
        await this.gmailService.markMessageRead(
          employeeId,
          message.gmailMessageId,
        );
      } catch (error: any) {
        this.logger.warn(
          `Could not mark Gmail message as read: ${
            error?.message ||
            error
          }`,
        );
      }

      await this.prisma.emailMessage.update(
        {
          where: {
            id:
              message.id,
          },

          data: {
            isRead:
              true,
          },
        },
      );
    }

    await this.prisma.emailThread.update(
      {
        where: {
          id:
            thread.id,
        },

        data: {
          unreadCount:
            0,
        },
      },
    );

    return {
      success:
        true,
    };
  }

  private normalizeKshetraSubject(
    subject: string,
  ): string {
    const trimmed =
      subject.trim();

    if (
      this.isKshetraSubject(
        trimmed,
      )
    ) {
      return trimmed;
    }

    return `[KSHETRA] ${trimmed}`;
  }

  private isKshetraSubject(
    subject?: string | null,
  ): boolean {
    return (
      !!subject &&
      subject
        .toUpperCase()
        .includes(
          '[KSHETRA]',
        )
    );
  }

  private ensureReplySubject(
    subject: string,
  ): string {
    if (
      /^re:/i.test(
        subject.trim(),
      )
    ) {
      return subject;
    }

    return `Re: ${subject}`;
  }

  private ensureForwardSubject(
    subject: string,
  ): string {
    const trimmed =
      subject.trim();

    if (
      /^fwd:/i.test(
        trimmed,
      )
    ) {
      return trimmed;
    }

    if (
      this.isKshetraSubject(
        trimmed,
      )
    ) {
      return `Fwd: ${trimmed}`;
    }

    return `[KSHETRA] Fwd: ${trimmed}`;
  }

  private isValidEmail(
    email: string,
  ): boolean {
    const emailRegex =
      /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    return emailRegex.test(
      email.trim(),
    );
  }

  private validateResolvedAttachments(
    attachments: ResolvedAttachment[],
  ): void {
    let totalSize = 0;

    for (const attachment of attachments) {
      if (
        !attachment.filename?.trim()
      ) {
        throw new BadRequestException(
          'Attachment filename is required.',
        );
      }

      const mimeType =
        attachment.mimeType
          .split(';')[0]
          .trim()
          .toLowerCase();

      if (
        !this.ALLOWED_ATTACHMENT_TYPES.includes(
          mimeType,
        )
      ) {
        throw new BadRequestException(
          `Attachment type is not allowed: ${mimeType}`,
        );
      }

      if (
        attachment.content.length >
        this.MAX_ATTACHMENT_SIZE
      ) {
        throw new BadRequestException(
          `Attachment "${attachment.filename}" exceeds the 10MB limit.`,
        );
      }

      totalSize +=
        attachment.content.length;
    }

    if (
      totalSize >
      this.MAX_TOTAL_ATTACHMENT_SIZE
    ) {
      throw new BadRequestException(
        'Total attachment size exceeds 20MB.',
      );
    }
  }

  private async resolveAttachments(
    employeeId: string,
    urls: string[],
  ): Promise<ResolvedAttachment[]> {
    if (!urls.length) {
      return [];
    }

    const attachments:
      ResolvedAttachment[] =
      [];

    for (const url of urls) {
      try {
        if (
          !this.isAllowedAttachmentUrl(
            employeeId,
            url,
          )
        ) {
          throw new BadRequestException(
            'Attachment URL is not allowed.',
          );
        }

        const attachment =
          await this.prisma.attachment.findFirst(
            {
              where: {
                fileUrl:
                  url,

                visit: {
                  employeeId,
                },
              },
            },
          );

        const isSitePhoto =
          url.includes(
            'site-photos/',
          );

        const isEmployeeEmailAttachment =
          url.includes(
            `/email-attachments/${employeeId}/`,
          );

        if (
          isSitePhoto &&
          !attachment
        ) {
          throw new ForbiddenException(
            'You do not have permission to attach this file.',
          );
        }

        if (
          !attachment &&
          !isEmployeeEmailAttachment
        ) {
          throw new ForbiddenException(
            'You do not have permission to attach this file.',
          );
        }

        const response =
          await fetch(url);

        if (!response.ok) {
          throw new Error(
            `Failed to fetch attachment: ${response.status} ${response.statusText}`,
          );
        }

        const buffer =
          Buffer.from(
            await response.arrayBuffer(),
          );

        const contentType =
          (
            response.headers.get(
              'content-type',
            ) ||
            'application/octet-stream'
          )
            .split(';')[0]
            .trim()
            .toLowerCase();

        const filename =
          decodeURIComponent(
            new URL(url).pathname
              .split('/')
              .pop() ||
              'attachment',
          );

        attachments.push({
          filename,
          mimeType:
            contentType,
          content:
            buffer,
        });
      } catch (error: any) {
        if (
          error instanceof
            BadRequestException ||
          error instanceof
            ForbiddenException
        ) {
          throw error;
        }

        this.logger.error(
          `Failed to resolve attachment: ${
            error?.message ||
            error
          }`,
        );

        throw new BadRequestException(
          `Failed to process attachment: ${
            error?.message ||
            error
          }`,
        );
      }
    }

    this.validateResolvedAttachments(
      attachments,
    );

    return attachments;
  }

  private async fetchVisitPhotos(
    visitAttachments: Array<{
      fileUrl: string;
      type: string;
    }>,
  ): Promise<ResolvedAttachment[]> {
    const photos:
      ResolvedAttachment[] =
      [];

    for (const attachment of visitAttachments) {
      if (
        attachment.type !==
        'image'
      ) {
        continue;
      }

      try {
        const response =
          await fetch(
            attachment.fileUrl,
          );

        if (!response.ok) {
          continue;
        }

        const buffer =
          Buffer.from(
            await response.arrayBuffer(),
          );

        const contentType =
          (
            response.headers.get(
              'content-type',
            ) ||
            'image/jpeg'
          )
            .split(';')[0]
            .trim()
            .toLowerCase();

        const filename =
          decodeURIComponent(
            new URL(
              attachment.fileUrl,
            ).pathname
              .split('/')
              .pop() ||
              'visit-photo.jpg',
          );

        if (
          buffer.length >
          this.MAX_ATTACHMENT_SIZE
        ) {
          this.logger.warn(
            `Skipping oversized photo: ${filename}`,
          );

          continue;
        }

        photos.push({
          filename,
          mimeType:
            contentType,
          content:
            buffer,
        });
      } catch (error: any) {
        this.logger.warn(
          `Failed to fetch visit photo: ${
            error?.message ||
            error
          }`,
        );
      }
    }

    return photos;
  }

  private isAllowedAttachmentUrl(
    employeeId: string,
    url: string,
  ): boolean {
    if (
      url.startsWith(
        '/uploads/',
      )
    ) {
      return true;
    }

    try {
      const parsed =
        new URL(url);

      if (
        parsed.protocol !==
        'https:' &&
        !(
          parsed.protocol ===
            'http:' &&
          (
            parsed.hostname ===
              'localhost' ||
            parsed.hostname ===
              '10.0.2.2'
          )
        )
      ) {
        return false;
      }

      const pathname =
        parsed.pathname;

      if (
        pathname.includes(
          'site-photos/',
        )
      ) {
        return true;
      }

      return pathname.includes(
        `/email-attachments/${employeeId}/`,
      );
    } catch {
      return false;
    }
  }

  private buildVisitReportBody(
    visit: any,
    additionalNotes?: string,
  ): string {
    const lines: string[] = [];

    lines.push(
      'FIELD VISIT REPORT',
    );

    lines.push(
      '═══════════════════════════════════════',
    );

    lines.push('');

    lines.push(
      `Visit ID: ${visit.id}`,
    );

    lines.push(
      `Employee: ${
        visit.employee?.name ||
        visit.employeeId
      } (${visit.employeeId})`,
    );

    lines.push(
      `Date: ${new Date(
        visit.timestamp,
      ).toLocaleString(
        'en-IN',
      )}`,
    );

    lines.push('');

    lines.push(
      '── Customer Details ──',
    );

    lines.push(
      `Customer/Site: ${
        visit.site?.name ||
        'Unknown'
      }`,
    );

    lines.push(
      `Address: ${
        visit.site?.address ||
        'N/A'
      }`,
    );

    lines.push('');

    if (visit.location) {
      lines.push(
        '── Visit Location ──',
      );

      lines.push(
        `GPS: ${visit.location.lat}, ${visit.location.lng}`,
      );

      if (
        visit.location.accuracy
      ) {
        lines.push(
          `Accuracy: ${visit.location.accuracy}m`,
        );
      }

      lines.push('');
    }

    if (
      visit.notes ||
      visit.remarks
    ) {
      lines.push(
        '── Notes / Remarks ──',
      );

      if (visit.notes) {
        lines.push(
          visit.notes,
        );
      }

      if (visit.remarks) {
        lines.push(
          visit.remarks,
        );
      }

      lines.push('');
    }

    if (
      visit.materials?.length >
      0
    ) {
      lines.push(
        '── Materials Supplied ──',
      );

      for (const material of visit.materials) {
        lines.push(
          `• ${
            material.material
              ?.name ||
            'Unknown'
          }: ${
            material.quantity
          } ${
            material.material
              ?.unit ||
            ''
          }`,
        );
      }

      lines.push('');
    }

    if (
      visit.followUps?.length >
      0
    ) {
      lines.push(
        '── Follow-ups ──',
      );

      for (const followUp of visit.followUps) {
        lines.push(
          `• Due: ${new Date(
            followUp.dueDate,
          ).toLocaleDateString(
            'en-IN',
          )} — Status: ${
            followUp.status
          }`,
        );

        if (followUp.notes) {
          lines.push(
            `  Notes: ${followUp.notes}`,
          );
        }
      }

      lines.push('');
    }

    lines.push(
      `Status: ${visit.status}`,
    );

    lines.push('');

    if (additionalNotes) {
      lines.push(
        '── Additional Notes ──',
      );

      lines.push(
        additionalNotes,
      );

      lines.push('');
    }

    lines.push(
      '═══════════════════════════════════════',
    );

    lines.push(
      'Sent via Kshetra Field Sales Management System',
    );

    return lines.join('\n');
  }

  private plainTextToHtml(
    text: string,
  ): string {
    return text
      .replace(
        /&/g,
        '&amp;',
      )
      .replace(
        /</g,
        '&lt;',
      )
      .replace(
        />/g,
        '&gt;',
      )
      .replace(
        /\n/g,
        '<br>',
      );
  }
}