import React, { useState } from 'react';
import { User, Phone, Lock, Save, AlertCircle } from 'lucide-react';
import { AddEmployeeForm } from '../types';

interface AddEmployeeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: AddEmployeeForm) => void;
  isLoading: boolean;
}

export const AddEmployeeModal: React.FC<AddEmployeeModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  isLoading,
}) => {
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!name.trim() || !password) {
      setError('Name and password are required.');
      return;
    }

    if (password.length < 4) {
      setError('Password/PIN must be at least 4 characters.');
      return;
    }

    onSubmit({
      name: name.trim(),
      phone: phone.trim(),
      password,
      employeeId: '', // Auto-generated by backend now
    });
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div 
        className="glass-panel w-full max-w-md overflow-hidden animate-in fade-in zoom-in-95 duration-200 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 py-5 border-b border-[var(--glass-border)] bg-[var(--glass-bg-primary)]">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-indigo-500/20 text-indigo-400 rounded-xl border border-indigo-500/30">
                <User size={20} />
              </div>
              <h2 className="text-xl font-bold text-[var(--text-main)]">Add New Employee</h2>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="p-2 rounded-xl text-[var(--text-main)] opacity-50 hover:opacity-100 hover:bg-[var(--glass-border)] transition-colors"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M18 6L6 18M6 6l12 12" />
              </svg>
            </button>
          </div>
          <p className="text-sm text-[var(--text-main)] opacity-60 mt-2">
            The system will automatically generate a unique Employee ID (e.g., SE-FS-001).
          </p>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          {error && (
            <div className="p-4 bg-rose-500/10 border border-rose-500/30 rounded-xl flex items-start gap-3">
              <AlertCircle size={18} className="text-rose-400 shrink-0 mt-0.5" />
              <p className="text-sm font-medium text-rose-400">{error}</p>
            </div>
          )}

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-[var(--text-main)] opacity-70 mb-2 ml-1">
                Full Name *
              </label>
              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-[var(--text-main)] opacity-40 group-focus-within:opacity-100 group-focus-within:text-indigo-400 transition-colors">
                  <User size={18} />
                </div>
                <input
                  type="text"
                  required
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. John Doe"
                  className="glass-input w-full pl-11 pr-4 py-3 text-sm placeholder:text-[var(--text-main)] placeholder:opacity-30"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-[var(--text-main)] opacity-70 mb-2 ml-1">
                Phone Number
              </label>
              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-[var(--text-main)] opacity-40 group-focus-within:opacity-100 group-focus-within:text-indigo-400 transition-colors">
                  <Phone size={18} />
                </div>
                <input
                  type="tel"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder="e.g. +91 9876543210"
                  className="glass-input w-full pl-11 pr-4 py-3 text-sm placeholder:text-[var(--text-main)] placeholder:opacity-30"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-[var(--text-main)] opacity-70 mb-2 ml-1">
                Password / Login PIN *
              </label>
              <div className="relative group">
                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-[var(--text-main)] opacity-40 group-focus-within:opacity-100 group-focus-within:text-indigo-400 transition-colors">
                  <Lock size={18} />
                </div>
                <input
                  type="text"
                  required
                  minLength={4}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="Minimum 4 characters"
                  className="glass-input w-full pl-11 pr-4 py-3 text-sm placeholder:text-[var(--text-main)] placeholder:opacity-30"
                />
              </div>
              <p className="text-[11px] text-[var(--text-main)] opacity-40 mt-1 ml-1">
                The employee will use this to log into the mobile app.
              </p>
            </div>
          </div>

          <div className="pt-4 flex gap-3">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-3 rounded-xl border border-[var(--glass-border)] text-[var(--text-main)] opacity-70 hover:opacity-100 hover:bg-white/5 font-bold text-sm transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isLoading}
              className="flex-1 flex justify-center items-center gap-2 px-4 py-3 bg-indigo-500 hover:bg-indigo-600 text-white rounded-xl font-bold text-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-[0_0_15px_rgba(99,102,241,0.4)]"
            >
              {isLoading ? (
                <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
              ) : (
                <>
                  <Save size={18} /> Add Employee
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};